'use client';

import { useEffect, useState } from 'react';
import { Banknote, FileText, Play, Printer, Settings2 } from 'lucide-react';
import { formatPKR } from '@/lib/utils';

interface Entry { id: string; payrollMonth: string; basicSalary: number; allowances: number; deductions: number; leaveDeduction: number; netSalary: number; status: string; employee: { id: string; fullName: string; role: string; department: string } }
interface Staff { id: string; fullName: string; role: string; department: string }

export function PayrollManagement({ canManage }: { canManage: boolean }) {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [entries, setEntries] = useState<Entry[]>([]);
  const [staff, setStaff] = useState<Staff[]>([]);
  const [form, setForm] = useState({ employeeId: '', basicSalary: '', allowances: '0', deductions: '0' });
  const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch(`/api/payroll?month=${month}`); const data = await response.json(); if (response.ok) setEntries(data.entries || []); };
  useEffect(() => { load(); if (canManage) fetch('/api/staff?status=ACTIVE').then((response) => response.json()).then((data) => setStaff(data.employees || [])); }, [month, canManage]);
  const post = async (body: Record<string, string>) => { const response = await fetch('/api/payroll', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || 'Payroll action failed'); return false; } return true; };
  const setStructure = async (event: React.FormEvent) => { event.preventDefault(); if (await post({ action: 'STRUCTURE', ...form })) { setMessage('Salary structure saved.'); setForm({ employeeId: '', basicSalary: '', allowances: '0', deductions: '0' }); } };
  const generate = async () => { if (await post({ action: 'GENERATE', month })) { setMessage('Payroll generated successfully.'); load(); } };
  const updateStatus = async (id: string, status: string) => { if (await post({ action: 'STATUS', id, status })) setEntries((current) => current.map((entry) => entry.id === id ? { ...entry, status } : entry)); };
  const printPayslip = (entry: Entry) => {
    const slip = window.open('', '_blank', 'width=820,height=720');
    if (!slip) return;
    slip.document.write(`<html><head><title>Payslip - ${entry.employee.fullName} - ${entry.payrollMonth}</title><style>body{font-family:Arial,sans-serif;color:#172033;padding:40px}header{border-bottom:3px solid #047857;padding-bottom:16px;margin-bottom:28px}h1{font-size:22px;margin:0;color:#064e3b}h2{font-size:16px;margin:4px 0;color:#047857}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:24px}.meta p{margin:0;padding:10px;background:#f1f5f9;font-size:12px}.rows{border:1px solid #cbd5e1;border-radius:8px;overflow:hidden}.row{display:flex;justify-content:space-between;padding:13px 16px;border-bottom:1px solid #e2e8f0;font-size:13px}.row:last-child{border:0}.net{font-size:18px;font-weight:bold;background:#ecfdf5;color:#047857}.muted{color:#64748b;font-size:11px;margin-top:30px}@media print{button{display:none}}</style></head><body><header><h1>PAKISTAN BAIT-UL-MAAL</h1><h2>Sweet Home Multan · Official Salary Payslip</h2></header><div class="meta"><p><b>Employee:</b> ${entry.employee.fullName}</p><p><b>Payroll Month:</b> ${entry.payrollMonth}</p><p><b>Designation:</b> ${entry.employee.role}</p><p><b>Department:</b> ${entry.employee.department}</p></div><div class="rows"><div class="row"><span>Basic Salary</span><b>${formatPKR(entry.basicSalary)}</b></div><div class="row"><span>Allowances</span><b>${formatPKR(entry.allowances)}</b></div><div class="row"><span>Standard Deductions</span><b>${formatPKR(entry.deductions)}</b></div><div class="row"><span>Approved Leave Deduction</span><b>${formatPKR(entry.leaveDeduction)}</b></div><div class="row net"><span>Net Payable Salary</span><b>${formatPKR(entry.netSalary)}</b></div></div><p class="muted">Generated from Sweet Home Multan ERP · Status: ${entry.status}</p><script>window.onload=()=>window.print()</script></body></html>`);
    slip.document.close();
  };
  const total = entries.reduce((sum, entry) => sum + entry.netSalary, 0);
  return <div className="space-y-6"><div className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-700">Finance & HR</p><h1 className="text-xl font-bold text-slate-900">Payroll & Salary</h1><p className="mt-1 text-xs text-slate-500">Generate monthly salaries with approved-leave deductions.</p></div><label className="text-xs font-semibold text-slate-600">Payroll month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="ml-2 rounded-lg border border-slate-300 px-2 py-1.5 text-xs" /></label></div>
    {message && <p className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">{message}</p>}
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Payroll entries" value={String(entries.length)} /><Metric label="Total net payroll" value={formatPKR(total)} /><Metric label="Paid entries" value={String(entries.filter((entry) => entry.status === 'PAID').length)} /></div>
    {canManage && <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1fr_auto]"><form onSubmit={setStructure} className="rounded-xl border border-slate-200 bg-white p-5 shadow-xs"><div className="mb-3 flex items-center gap-2"><Settings2 className="h-4 w-4 text-emerald-700" /><h2 className="text-sm font-bold text-slate-800">Salary Structure</h2></div><div className="grid gap-3 sm:grid-cols-4"><select required value={form.employeeId} onChange={(event) => setForm({ ...form, employeeId: event.target.value })} className="rounded-lg border border-slate-300 px-2 py-2 text-xs"><option value="">Select staff</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select><input required type="number" min="0" placeholder="Basic salary" value={form.basicSalary} onChange={(event) => setForm({ ...form, basicSalary: event.target.value })} className="rounded-lg border border-slate-300 px-2 py-2 text-xs" /><input type="number" min="0" placeholder="Allowances" value={form.allowances} onChange={(event) => setForm({ ...form, allowances: event.target.value })} className="rounded-lg border border-slate-300 px-2 py-2 text-xs" /><input type="number" min="0" placeholder="Deductions" value={form.deductions} onChange={(event) => setForm({ ...form, deductions: event.target.value })} className="rounded-lg border border-slate-300 px-2 py-2 text-xs" /></div><button className="mt-3 rounded-lg bg-slate-800 px-3 py-2 text-xs font-bold text-white">Save salary structure</button></form><button onClick={generate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-xs font-bold text-white shadow-xs"><Play className="h-4 w-4" />Generate month</button></div>}
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-xs"><div className="mb-4 flex items-center gap-2 border-b border-slate-100 pb-3"><Banknote className="h-4 w-4 text-emerald-700" /><h2 className="text-sm font-bold text-slate-800">{month} Payroll Entries</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-200 text-slate-500"><tr><th className="px-2 py-2">Employee</th><th className="px-2 py-2">Basic</th><th className="px-2 py-2">Leave deduction</th><th className="px-2 py-2">Net salary</th><th className="px-2 py-2">Status</th><th className="px-2 py-2">Payslip</th></tr></thead><tbody className="divide-y divide-slate-100">{entries.map((entry) => <tr key={entry.id}><td className="px-2 py-3"><strong>{entry.employee.fullName}</strong><span className="block text-[10px] text-slate-400">{entry.employee.role} · {entry.employee.department}</span></td><td className="px-2 py-3">{formatPKR(entry.basicSalary)}</td><td className="px-2 py-3 text-amber-700">{formatPKR(entry.leaveDeduction)}</td><td className="px-2 py-3 font-bold text-emerald-700">{formatPKR(entry.netSalary)}</td><td className="px-2 py-3">{canManage ? <select value={entry.status} onChange={(event) => updateStatus(entry.id, event.target.value)} className="rounded-md border border-slate-300 px-2 py-1 text-[10px]"><option>DRAFT</option><option>APPROVED</option><option>PAID</option></select> : <span className="font-bold">{entry.status}</span>}</td><td className="px-2 py-3"><button onClick={() => printPayslip(entry)} title="Print payslip" className="inline-flex items-center gap-1 rounded-md border border-emerald-200 px-2 py-1 text-[10px] font-bold text-emerald-700 hover:bg-emerald-50"><Printer className="h-3 w-3" />Payslip</button></td></tr>)}</tbody></table>{entries.length === 0 && <p className="py-8 text-center text-xs text-slate-500">No payroll entries for this month. Set salary structures and generate payroll.</p>}</div></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xl font-extrabold text-slate-900">{value}</p></div>; }
