'use client';

import { useEffect, useState } from 'react';
import { FileText, Trash2, UploadCloud } from 'lucide-react';
import { formatDate } from '@/lib/utils';

interface ChildDocument { id: string; title: string; documentType: string; fileSize: string | null; uploadedAt: string }

export function ChildDocumentsSection({ childId, canManage }: { childId: string; canManage: boolean }) {
  const [documents, setDocuments] = useState<ChildDocument[]>([]);
  const [title, setTitle] = useState('');
  const [documentType, setDocumentType] = useState('B_FORM');
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch(`/api/children/${childId}/documents`); const data = await response.json(); if (response.ok) setDocuments(data.documents || []); };
  useEffect(() => { load(); }, [childId]);
  const upload = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !title.trim()) return; const formData = new FormData(); formData.append('file', file); formData.append('title', title); formData.append('documentType', documentType); const response = await fetch(`/api/children/${childId}/documents`, { method: 'POST', body: formData }); const data = await response.json(); setMessage(response.ok ? 'Document uploaded successfully.' : data.error || 'Upload failed'); if (response.ok) { setTitle(''); setFile(null); load(); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this document?')) return; const response = await fetch(`/api/children/${childId}/documents?documentId=${id}`, { method: 'DELETE' }); if (response.ok) setDocuments((current) => current.filter((document) => document.id !== id)); };
  return <section className="rounded-xl border border-blue-200 bg-blue-50/30 p-5 shadow-xs"><div className="mb-4 flex items-center gap-2 border-b border-blue-100 pb-3"><FileText className="h-4 w-4 text-blue-700" /><div><span className="text-[10px] font-bold text-blue-700">DOCUMENT VAULT</span><h2 className="text-sm font-bold text-slate-800">Child Documents</h2></div></div>{canManage && <form onSubmit={upload} className="grid gap-3 md:grid-cols-[150px_1fr_1fr_auto] md:items-end"><label className="text-xs font-semibold text-slate-600">Document type<select value={documentType} onChange={(event) => setDocumentType(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2 py-2 text-xs"><option>B_FORM</option><option>BIRTH_CERTIFICATE</option><option>ADMISSION_FORM</option><option>MEDICAL_REPORT</option><option>SCHOOL_RECORD</option><option>OTHER</option></select></label><label className="text-xs font-semibold text-slate-600">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Original B-Form" className="mt-1 w-full rounded-lg border border-slate-300 px-2 py-2 text-xs" /></label><label className="text-xs font-semibold text-slate-600">File<input required type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs" /></label><button className="inline-flex items-center justify-center gap-1 rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white"><UploadCloud className="h-3.5 w-3.5" />Upload</button></form>}{message && <p className="mt-3 text-xs font-semibold text-blue-700">{message}</p>}<div className="mt-4 space-y-2">{documents.length === 0 ? <p className="text-xs text-slate-500">No documents uploaded for this child.</p> : documents.map((document) => <div key={document.id} className="flex items-center justify-between rounded-lg border border-white bg-white p-3"><a href={`/api/children/${childId}/documents?documentId=${document.id}`} target="_blank" rel="noreferrer" className="min-w-0"><span className="block truncate text-xs font-bold text-blue-800 hover:underline">{document.title}</span><span className="text-[10px] text-slate-500">{document.documentType} · {document.fileSize || 'File'} · {formatDate(document.uploadedAt)}</span></a>{canManage && <button type="button" onClick={() => remove(document.id)} title="Delete document" className="p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-3.5 w-3.5" /></button>}</div>)}</div></section>;
}
